baseURL: https://parthivibansal.netlify.app/
languageCode: en-us
title: Portfolio Website for Parthivi 
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: This is a small exhibit of my coding and analytical work! 
    title: Hi, Welcome to Parthivi's Portfolio!
  blog: {}
  contact:
    address:
      - city: London, NW8 8UN 
        country: United Kingdom 
        street: Palgrave Gardens 
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: pbansal.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (123) 123-1234 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-github
        label: GitHub
        url: https://github.com/parthivibansal/
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/parthivibansal/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: My Portfolio
        url: '#'
      - name: About Me!
        url: blogs/me
      - name: 
        url: blogs/ipsum
      - name: My stock reports 
        url: blogs/cipla1
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: youth.jpg
        #subtitle: Ipsum Dolor Sit Amet
        title: Lets see what is influencing the youth?
        url: blogs/youth
      - image: bike.jpg
        #subtitle: Feugiat Amet Tempus
        title: Excess rentals in TfL bike sharing!
        url: blogs/bike
      #image: pic03.jpg
        #subtitle: Lorem Etiam Nullam
        #title: Magna
        #url: blogs/magna
      - image: stocks.jpg
        #subtitle: Nisl Sed Aliquam
        title: Analysis of financial returns of DJIA
        url: blogs/stock
      - image: yieldcurve.jpg
        #subtitle: 
        title: Yield Curve Visualisssations!
        url: blogs/yieldcurve
      - image: inflation .jpgblog
        #subtitle: Assignment
        title: Inflation and CPI Analysis
        url: blogs/inflation
  two:
    buttonText: Get Started
    enable: yes
    subtitle: " The visualisations on this page show analysis of huge chunks of data through
      \n   boxplots, line plots and other graphs. They majorly focus on Exploratory data analysis
      and Inferential Statistics."
    title: About my work
    url: blogs
